[mongodb]
mongodb.joindevops07.shop
[catalogue]
catalogue.joindevops07.shop
[user]
user.joindevops07.shop
[cart]
cart.joindevops07.shop
[frontend]
frontend.joindevops07.shop
[redis]
redis.joindevops07.shop
[mysql]
mysql.joindevops07.shop
[shipping]
shipping.joindevops07.shop
[rabbitmq]
rabbitmq.joindevops07.shop
[payment]
payment.joindevops07.shop

